import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "../components/layouts/footer";
import { motion } from "framer-motion";
import Navbar from "../components/navbar";
import { UserProvider } from "../context/user-context";
import { ThemeProvider } from "next-themes";
import { ToasterProvider } from "../components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          themes={["light", "dark"]}
          forcedTheme="dark"
        >
          <UserProvider>
            <ToasterProvider>
              <div className="flex min-h-screen flex-col">
                <Navbar />

                {children}

                <Footer />
              </div>
            </ToasterProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
